# 1. Always start with the version
version: '3.8'

# 2. Define the services (containers)
services:
  # 3. Name of the service (you choose)
  postgres:
    # 4. What image to use?
    image: postgres:15
    
    # 5. What name to give to the container?
    container_name: notes-postgres
    
    # 6. What environment variables does PostgreSQL need?
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    # 7. What ports to expose? format: port-local:port-container
    ports:
      - "5432:5432"
    
    # 8. What volumes to mount?
    volumes:
      # To persist data: named-volume:path-in-container
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. Name of the service (you choose)
  app:
    # 4. What image to use?
    build: . # Build from dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 3000
      NODE_ENV: development

# 9. Define the named volumes we used above
volumes:
  postgres_data:  # Docker will create and manage this volume